//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration;

namespace ShepAsyncHttp
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class ErrorInfo
    {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorDataField;
        
        private System.DateTime errorDateField;
        
        private ErrorInfo subErrorField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorData
        {
            get
            {
                return this.errorDataField;
            }
            set
            {
                this.errorDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime errorDate
        {
            get
            {
                return this.errorDateField;
            }
            set
            {
                this.errorDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ErrorInfo subError
        {
            get
            {
                return this.subErrorField;
            }
            set
            {
                this.subErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncGetMessageStatusResponse
    {
        
        private MessageState messageStateField;
        
        private MessageStatusInfo statusField;
        
        private System.DateTime responseDateField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public MessageState messageState
        {
            get
            {
                return this.messageStateField;
            }
            set
            {
                this.messageStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageStatusInfo status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime responseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public enum MessageState
    {
        
        /// <remarks/>
        ON_DELIVERY,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        NOT_DELIVERED,
        
        /// <remarks/>
        DELIVERY_STOPPED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class MessageStatusInfo
    {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private System.DateTime statusDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime statusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncSendDeliveryNotificationRequest
    {
        
        private DeliveryNotification notificationField;
        
        private System.DateTime requestDateField;
        
        private SenderInfo senderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DeliveryNotification notification
        {
            get
            {
                return this.notificationField;
            }
            set
            {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime requestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SenderInfo sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class DeliveryNotification
    {
        
        private string messageIdField;
        
        private string serviceIdField;
        
        private System.DateTime notificationDateField;
        
        private DeliveryStatusInfo deliveryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime notificationDate
        {
            get
            {
                return this.notificationDateField;
            }
            set
            {
                this.notificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DeliveryStatusInfo deliveryStatus
        {
            get
            {
                return this.deliveryStatusField;
            }
            set
            {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class DeliveryStatusInfo
    {
        
        private DeliveryStatusInfoReceiveStatus receiveStatusField;
        
        private System.DateTime statusDateField;
        
        private DeliveryStatusInfoResendMessage resendMessageField;
        
        private ErrorInfo errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DeliveryStatusInfoReceiveStatus receiveStatus
        {
            get
            {
                return this.receiveStatusField;
            }
            set
            {
                this.receiveStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime statusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DeliveryStatusInfoResendMessage resendMessage
        {
            get
            {
                return this.resendMessageField;
            }
            set
            {
                this.resendMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ErrorInfo error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/common/v10/Types")]
    public enum DeliveryStatusInfoReceiveStatus
    {
        
        /// <remarks/>
        MESSAGE_ACCEPTED,
        
        /// <remarks/>
        MESSAGE_NOT_ACCTEPTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/common/v10/Types")]
    public enum DeliveryStatusInfoResendMessage
    {
        
        /// <remarks/>
        RESEND,
        
        /// <remarks/>
        NOT_RESEND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class SenderInfo
    {
        
        private string senderIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string senderId
        {
            get
            {
                return this.senderIdField;
            }
            set
            {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncSendMessageResponse
    {
        
        private string messageIdField;
        
        private string correlationIdField;
        
        private System.DateTime responseDateField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime responseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncGetMessagesResponse
    {
        
        private System.DateTime responseDateField;
        
        private string sessionIdField;
        
        private AsyncMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime responseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AsyncMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncMessage
    {
        
        private AsyncMessageInfo messageInfoField;
        
        private MessageData messageDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AsyncMessageInfo messageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageData messageData
        {
            get
            {
                return this.messageDataField;
            }
            set
            {
                this.messageDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncMessageInfo
    {
        
        private string messageIdField;
        
        private string correlationIdField;
        
        private string serviceIdField;
        
        private AsyncMessageInfoMessageType messageTypeField;
        
        private string routeIdField;
        
        private System.DateTime messageDateField;
        
        private SenderInfo senderField;
        
        private Property[] propertiesField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public AsyncMessageInfoMessageType messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string routeId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime messageDate
        {
            get
            {
                return this.messageDateField;
            }
            set
            {
                this.messageDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public SenderInfo sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Property[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public enum AsyncMessageInfoMessageType
    {
        
        /// <remarks/>
        REQUEST,
        
        /// <remarks/>
        NOTIFICATION,
        
        /// <remarks/>
        UPDATE,
        
        /// <remarks/>
        RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/common/v10/Types")]
    public partial class Property
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class MessageData
    {
        
        private object dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("data", typeof(GbdflMessageData))]
        public object data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncGetMessagesRequest
    {
        
        private string messageIdField;
        
        private string correlationIdField;
        
        private System.DateTime requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private string serviceIdField;
        
        private SenderInfo senderField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private Property[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime requestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestDateSpecified
        {
            get
            {
                return this.requestDateFieldSpecified;
            }
            set
            {
                this.requestDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SenderInfo sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Property[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncGetMessageStatusRequest
    {
        
        private string messageIdField;
        
        private System.DateTime requestDateField;
        
        private SenderInfo senderField;
        
        private Property[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime requestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SenderInfo sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Property[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncSendDeliveryNotificationResponse
    {
        
        private string notificationIdField;
        
        private System.DateTime responseDateField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string notificationId
        {
            get
            {
                return this.notificationIdField;
            }
            set
            {
                this.notificationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime responseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/ITypes")]
    public partial class AsyncSendMessageRequest
    {
        
        private AsyncMessageInfo messageInfoField;
        
        private MessageData messageDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AsyncMessageInfo messageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageData messageData
        {
            get
            {
                return this.messageDataField;
            }
            set
            {
                this.messageDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Interfaces", ConfigurationName="ShepAsyncHttp.IAsyncChannel")]
    public interface IAsyncChannel
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShepAsyncHttp.ErrorInfo), Action="", Name="sendMessageFault1_sendMessageFault", Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationResponse))]
        System.Threading.Tasks.Task<ShepAsyncHttp.sendMessageResponse1> sendMessageAsync(ShepAsyncHttp.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShepAsyncHttp.ErrorInfo), Action="", Name="sendDeliveryNotificationFault1_sendDeliveryNotificationFault", Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationResponse))]
        System.Threading.Tasks.Task<ShepAsyncHttp.sendDeliveryNotificationResponse1> sendDeliveryNotificationAsync(ShepAsyncHttp.sendDeliveryNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShepAsyncHttp.ErrorInfo), Action="", Name="getMessageStatusFault1_getMessageStatusFault", Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationResponse))]
        System.Threading.Tasks.Task<ShepAsyncHttp.getMessageStatusResponse1> getMessageStatusAsync(ShepAsyncHttp.getMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShepAsyncHttp.ErrorInfo), Action="", Name="getMessagesFault1_getMessagesFault", Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessagesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncGetMessageStatusRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AsyncSendDeliveryNotificationResponse))]
        System.Threading.Tasks.Task<ShepAsyncHttp.getMessagesResponse1> getMessagesAsync(ShepAsyncHttp.getMessagesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class sendMessage
    {
        
        private AsyncSendMessageRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncSendMessageRequest request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class sendMessageResponse
    {
        
        private AsyncSendMessageResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncSendMessageResponse response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.sendMessage sendMessage;
        
        public sendMessageRequest()
        {
        }
        
        public sendMessageRequest(ShepAsyncHttp.sendMessage sendMessage)
        {
            this.sendMessage = sendMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.sendMessageResponse sendMessageResponse;
        
        public sendMessageResponse1()
        {
        }
        
        public sendMessageResponse1(ShepAsyncHttp.sendMessageResponse sendMessageResponse)
        {
            this.sendMessageResponse = sendMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class sendDeliveryNotification
    {
        
        private AsyncSendDeliveryNotificationRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncSendDeliveryNotificationRequest request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class sendDeliveryNotificationResponse
    {
        
        private AsyncSendDeliveryNotificationResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncSendDeliveryNotificationResponse response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDeliveryNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.sendDeliveryNotification sendDeliveryNotification;
        
        public sendDeliveryNotificationRequest()
        {
        }
        
        public sendDeliveryNotificationRequest(ShepAsyncHttp.sendDeliveryNotification sendDeliveryNotification)
        {
            this.sendDeliveryNotification = sendDeliveryNotification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDeliveryNotificationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.sendDeliveryNotificationResponse sendDeliveryNotificationResponse;
        
        public sendDeliveryNotificationResponse1()
        {
        }
        
        public sendDeliveryNotificationResponse1(ShepAsyncHttp.sendDeliveryNotificationResponse sendDeliveryNotificationResponse)
        {
            this.sendDeliveryNotificationResponse = sendDeliveryNotificationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class getMessageStatus
    {
        
        private AsyncGetMessageStatusRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncGetMessageStatusRequest request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class getMessageStatusResponse
    {
        
        private AsyncGetMessageStatusResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncGetMessageStatusResponse response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.getMessageStatus getMessageStatus;
        
        public getMessageStatusRequest()
        {
        }
        
        public getMessageStatusRequest(ShepAsyncHttp.getMessageStatus getMessageStatus)
        {
            this.getMessageStatus = getMessageStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.getMessageStatusResponse getMessageStatusResponse;
        
        public getMessageStatusResponse1()
        {
        }
        
        public getMessageStatusResponse1(ShepAsyncHttp.getMessageStatusResponse getMessageStatusResponse)
        {
            this.getMessageStatusResponse = getMessageStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class getMessages
    {
        
        private AsyncGetMessagesRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncGetMessagesRequest request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bip.bee.kz/AsyncChannel/v10/Types")]
    public partial class getMessagesResponse
    {
        
        private AsyncGetMessagesResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AsyncGetMessagesResponse response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.getMessages getMessages;
        
        public getMessagesRequest()
        {
        }
        
        public getMessagesRequest(ShepAsyncHttp.getMessages getMessages)
        {
            this.getMessages = getMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bip.bee.kz/AsyncChannel/v10/Types", Order=0)]
        public ShepAsyncHttp.getMessagesResponse getMessagesResponse;
        
        public getMessagesResponse1()
        {
        }
        
        public getMessagesResponse1(ShepAsyncHttp.getMessagesResponse getMessagesResponse)
        {
            this.getMessagesResponse = getMessagesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IAsyncChannelChannel : ShepAsyncHttp.IAsyncChannel, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AsyncChannelClient : System.ServiceModel.ClientBase<ShepAsyncHttp.IAsyncChannel>, ShepAsyncHttp.IAsyncChannel
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AsyncChannelClient() : 
                base(AsyncChannelClient.GetDefaultBinding(), AsyncChannelClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AsyncChannelHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AsyncChannelClient(EndpointConfiguration endpointConfiguration) : 
                base(AsyncChannelClient.GetBindingForEndpoint(endpointConfiguration), AsyncChannelClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AsyncChannelClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AsyncChannelClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AsyncChannelClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AsyncChannelClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AsyncChannelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShepAsyncHttp.sendMessageResponse1> ShepAsyncHttp.IAsyncChannel.sendMessageAsync(ShepAsyncHttp.sendMessageRequest request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShepAsyncHttp.sendMessageResponse1> sendMessageAsync(ShepAsyncHttp.sendMessage sendMessage)
        {
            ShepAsyncHttp.sendMessageRequest inValue = new ShepAsyncHttp.sendMessageRequest();
            inValue.sendMessage = sendMessage;
            return ((ShepAsyncHttp.IAsyncChannel)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShepAsyncHttp.sendDeliveryNotificationResponse1> ShepAsyncHttp.IAsyncChannel.sendDeliveryNotificationAsync(ShepAsyncHttp.sendDeliveryNotificationRequest request)
        {
            return base.Channel.sendDeliveryNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShepAsyncHttp.sendDeliveryNotificationResponse1> sendDeliveryNotificationAsync(ShepAsyncHttp.sendDeliveryNotification sendDeliveryNotification)
        {
            ShepAsyncHttp.sendDeliveryNotificationRequest inValue = new ShepAsyncHttp.sendDeliveryNotificationRequest();
            inValue.sendDeliveryNotification = sendDeliveryNotification;
            return ((ShepAsyncHttp.IAsyncChannel)(this)).sendDeliveryNotificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShepAsyncHttp.getMessageStatusResponse1> ShepAsyncHttp.IAsyncChannel.getMessageStatusAsync(ShepAsyncHttp.getMessageStatusRequest request)
        {
            return base.Channel.getMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShepAsyncHttp.getMessageStatusResponse1> getMessageStatusAsync(ShepAsyncHttp.getMessageStatus getMessageStatus)
        {
            ShepAsyncHttp.getMessageStatusRequest inValue = new ShepAsyncHttp.getMessageStatusRequest();
            inValue.getMessageStatus = getMessageStatus;
            return ((ShepAsyncHttp.IAsyncChannel)(this)).getMessageStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShepAsyncHttp.getMessagesResponse1> ShepAsyncHttp.IAsyncChannel.getMessagesAsync(ShepAsyncHttp.getMessagesRequest request)
        {
            return base.Channel.getMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShepAsyncHttp.getMessagesResponse1> getMessagesAsync(ShepAsyncHttp.getMessages getMessages)
        {
            ShepAsyncHttp.getMessagesRequest inValue = new ShepAsyncHttp.getMessagesRequest();
            inValue.getMessages = getMessages;
            return ((ShepAsyncHttp.IAsyncChannel)(this)).getMessagesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AsyncChannelHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AsyncChannelHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9080/SerrviceSampleTypesWeb/sca/AsyncChannelService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AsyncChannelClient.GetBindingForEndpoint(EndpointConfiguration.AsyncChannelHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AsyncChannelClient.GetEndpointAddress(EndpointConfiguration.AsyncChannelHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AsyncChannelHttpPort,
        }
    }
}
